export const getPositionX = (value: string | number) => {
    console.log(value, "getPositionX")
    switch (value) {
        case 1:
            return `left-[1%]`;
        case 2:
            return `left-[2%]`;
        case 3:
            return `left-[3%]`;
        case 4:
            return `left-[4%]`;
        case 5:
            return `left-[5%]`;
        case 6:
            return `left-[6%]`;
        case 7:
            return `left-[7%]`;
        case 8:
            return `left-[8%]`;
        case 9:
            return `left-[9%]`;
        case 10:
            return `left-[10%]`;
        case 11:
            return `left-[11%]`;
        case 12:
            return `left-[12%]`;
        case 13:
            return `left-[13%]`;
        case 14:
            return `left-[14%]`;
        case 15:
            return `left-[15%]`;
        case 16:
            return `left-[16%]`;
        case 17:
            return `left-[17%]`;
        case 18:
            return `left-[18%]`;
        case 19:
            return `left-[19%]`;
        case 20:
            return `left-[20%]`;
        case 21:
            return `left-[21%]`;
        case 22:
            return `left-[22%]`;
        case 23:
            return `left-[23%]`;
        case 24:
            return `left-[24%]`;
        case 25:
            return `left-[25%]`;
        case 26:
            return `left-[26%]`;
        case 27:
            return `left-[27%]`;
        case 28:
            return `left-[28%]`;
        case 29:
            return `left-[29%]`;
        case 30:
            return `left-[30%]`;
        case 31:
            return `left-[31%]`;
        case 32:
            return `left-[32%]`;
        case 33:
            return `left-[33%]`;
        case 34:
            return `left-[34%]`;
        case 35:
            return `left-[35%]`;
        case 36:
            return `left-[36%]`;
        case 37:
            return `left-[37%]`;
        case 38:
            return `left-[38%]`;
        case 39:
            return `left-[39%]`;
        case 40:
            return `left-[40%]`;
        case 41:
            return `left-[41%]`;
        case 42:
            return `left-[42%]`;
        case 43:
            return `left-[43%]`;
        case 44:
            return `left-[44%]`;
        case 45:
            return `left-[45%]`;
        case 46:
            return `left-[46%]`;
        case 47:
            return `left-[47%]`;
        case 48:
            return `left-[48%]`;
        case 49:
            return `left-[49%]`;
        case 50:
            return `left-[50%]`;
        case 51:
            return `left-[51%]`;
        case 52:
            return `left-[52%]`;
        case 53:
            return `left-[53%]`;
        case 54:
            return `left-[54%]`;
        case 55:
            return `left-[55%]`;
        case 56:
            return `left-[56%]`;
        case 57:
            return `left-[57%]`;
        case 58:
            return `left-[58%]`;
        case 59:
            return `left-[59%]`;
        case 60:
            return `left-[60%]`;
        case 61:
            return `left-[61%]`;
        case 62:
            return `left-[62%]`;
        case 63:
            return `left-[63%]`;
        case 64:
            return `left-[64%]`;
        case 65:
            return `left-[65%]`;
        case 66:
            return `left-[66%]`;
        case 67:
            return `left-[67%]`;
        case 68:
            return `left-[68%]`;
        case 69:
            return `left-[69%]`;
        case 70:
            return `left-[70%]`;
        case 71:
            return `left-[71%]`;
        case 72:
            return `left-[72%]`;
        case 73:
            return `left-[73%]`;
        case 74:
            return `left-[74%]`;
        case 75:
            return `left-[75%]`;
        case 76:
            return `left-[76%]`;
        case 77:
            return `left-[77%]`;
        case 78:
            return `left-[78%]`;
        case 79:
            return `left-[79%]`;
        case 80:
            return `left-[80%]`;
        case 81:
            return `left-[81%]`;
        case 82:
            return `left-[82%]`;
        case 83:
            return `left-[83%]`;
        case 84:
            return `left-[84%]`;
        case 85:
            return `left-[85%]`;
        case 86:
            return `left-[86%]`;
        case 87:
            return `left-[87%]`;
        case 88:
            return `left-[88%]`;
        case 89:
            return `left-[89%]`;
        case 90:
            return `left-[90%]`;
        case 91:
            return `left-[91%]`;
        case 92:
            return `left-[92%]`;
        case 93:
            return `left-[93%]`;
        case 94:
            return `left-[94%]`;
        case 95:
            return `left-[95%]`;
        case 96:
            return `left-[96%]`;
        case 97:
            return `left-[97%]`;
        case 98:
            return `left-[98%]`;
        case 99:
            return `left-[99%]`;
        case 100:
            return `left-[100%]`;
        default:
            return `left-[${value}%]`;
    }
}


export const getPositionY = (value: string | number) => {
    console.log(value, "getPositionY")
    switch (value) {
        case 1:
            return `bottom-[1%]`;
        case 2:
            return `bottom-[2%]`;
        case 3:
            return `bottom-[3%]`;
        case 4:
            return `bottom-[4%]`;
        case 5:
            return `bottom-[5%]`;
        case 6:
            return `bottom-[6%]`;
        case 7:
            return `bottom-[7%]`;
        case 8:
            return `bottom-[8%]`;
        case 9:
            return `bottom-[9%]`;
        case 10:
            return `bottom-[10%]`;
        case 11:
            return `bottom-[11%]`;
        case 12:
            return `bottom-[12%]`;
        case 13:
            return `bottom-[13%]`;
        case 14:
            return `bottom-[14%]`;
        case 15:
            return `bottom-[15%]`;
        case 16:
            return `bottom-[16%]`;
        case 17:
            return `bottom-[17%]`;
        case 18:
            return `bottom-[18%]`;
        case 19:
            return `bottom-[19%]`;
        case 20:
            return `bottom-[20%]`;
        case 21:
            return `bottom-[21%]`;
        case 22:
            return `bottom-[22%]`;
        case 23:
            return `bottom-[23%]`;
        case 24:
            return `bottom-[24%]`;
        case 25:
            return `bottom-[25%]`;
        case 26:
            return `bottom-[26%]`;
        case 27:
            return `bottom-[27%]`;
        case 28:
            return `bottom-[28%]`;
        case 29:
            return `bottom-[29%]`;
        case 30:
            return `bottom-[30%]`;
        case 31:
            return `bottom-[31%]`;
        case 32:
            return `bottom-[32%]`;
        case 33:
            return `bottom-[33%]`;
        case 34:
            return `bottom-[34%]`;
        case 35:
            return `bottom-[35%]`;
        case 36:
            return `bottom-[36%]`;
        case 37:
            return `bottom-[37%]`;
        case 38:
            return `bottom-[38%]`;
        case 39:
            return `bottom-[39%]`;
        case 40:
            return `bottom-[40%]`;
        case 41:
            return `bottom-[41%]`;
        case 42:
            return `bottom-[42%]`;
        case 43:
            return `bottom-[43%]`;
        case 44:
            return `bottom-[44%]`;
        case 45:
            return `bottom-[45%]`;
        case 46:
            return `bottom-[46%]`;
        case 47:
            return `bottom-[47%]`;
        case 48:
            return `bottom-[48%]`;
        case 49:
            return `bottom-[49%]`;
        case 50:
            return `bottom-[50%]`;
        case 51:
            return `bottom-[51%]`;
        case 52:
            return `bottom-[52%]`;
        case 53:
            return `bottom-[53%]`;
        case 54:
            return `bottom-[54%]`;
        case 55:
            return `bottom-[55%]`;
        case 56:
            return `bottom-[56%]`;
        case 57:
            return `bottom-[57%]`;
        case 58:
            return `bottom-[58%]`;
        case 59:
            return `bottom-[59%]`;
        case 60:
            return `bottom-[60%]`;
        case 61:
            return `bottom-[61%]`;
        case 62:
            return `bottom-[62%]`;
        case 63:
            return `bottom-[63%]`;
        case 64:
            return `bottom-[64%]`;
        case 65:
            return `bottom-[65%]`;
        case 66:
            return `bottom-[66%]`;
        case 67:
            return `bottom-[67%]`;
        case 68:
            return `bottom-[68%]`;
        case 69:
            return `bottom-[69%]`;
        case 70:
            return `bottom-[70%]`;
        case 71:
            return `bottom-[71%]`;
        case 72:
            return `bottom-[72%]`;
        case 73:
            return `bottom-[73%]`;
        case 74:
            return `bottom-[74%]`;
        case 75:
            return `bottom-[75%]`;
        case 76:
            return `bottom-[76%]`;
        case 77:
            return `bottom-[77%]`;
        case 78:
            return `bottom-[78%]`;
        case 79:
            return `bottom-[79%]`;
        case 80:
            return `bottom-[80%]`;
        case 81:
            return `bottom-[81%]`;
        case 82:
            return `bottom-[82%]`;
        case 83:
            return `bottom-[83%]`;
        case 84:
            return `bottom-[84%]`;
        case 85:
            return `bottom-[85%]`;
        case 86:
            return `bottom-[86%]`;
        case 87:
            return `bottom-[87%]`;
        case 88:
            return `bottom-[88%]`;
        case 89:
            return `bottom-[89%]`;
        case 90:
            return `bottom-[90%]`;
        case 91:
            return `bottom-[91%]`;
        case 92:
            return `bottom-[92%]`;
        case 93:
            return `bottom-[93%]`;
        case 94:
            return `bottom-[94%]`;
        case 95:
            return `bottom-[95%]`;
        case 96:
            return `bottom-[96%]`;
        case 97:
            return `bottom-[97%]`;
        case 98:
            return `bottom-[98%]`;
        case 99:
            return `bottom-[99%]`;
        case 100:
            return `bottom-[100%]`;
        default:
            return `bottom-[${value}%]`;
    }
}

const getWidth = (value) => {
    switch (value) {
        case 1:
            return `width-[1%]`;
        case 2:
            return `width-[2%]`;
        case 3:
            return `width-[3%]`;
        case 4:
            return `width-[4%]`;
        case 5:
            return `width-[5%]`;
        case 6:
            return `width-[6%]`;
        case 7:
            return `width-[7%]`;
        case 8:
            return `width-[8%]`;
        case 9:
            return `width-[9%]`;
        case 10:
            return `width-[10%]`;
        case 11:
            return `width-[11%]`;
        case 12:
            return `width-[12%]`;
        case 13:
            return `width-[13%]`;
        case 14:
            return `width-[14%]`;
        case 15:
            return `width-[15%]`;
        case 16:
            return `width-[16%]`;
        case 17:
            return `width-[17%]`;
        case 18:
            return `width-[18%]`;
        case 19:
            return `width-[19%]`;
        case 20:
            return `width-[20%]`;
        case 21:
            return `width-[21%]`;
        case 22:
            return `width-[22%]`;
        case 23:
            return `width-[23%]`;
        case 24:
            return `width-[24%]`;
        case 25:
            return `width-[25%]`;
        case 26:
            return `width-[26%]`;
        case 27:
            return `width-[27%]`;
        case 28:
            return `width-[28%]`;
        case 29:
            return `width-[29%]`;
        case 30:
            return `width-[30%]`;
        case 31:
            return `width-[31%]`;
        case 32:
            return `width-[32%]`;
        case 33:
            return `width-[33%]`;
        case 34:
            return `width-[34%]`;
        case 35:
            return `width-[35%]`;
        case 36:
            return `width-[36%]`;
        case 37:
            return `width-[37%]`;
        case 38:
            return `width-[38%]`;
        case 39:
            return `width-[39%]`;
        case 40:
            return `width-[40%]`;
        case 41:
            return `width-[41%]`;
        case 42:
            return `width-[42%]`;
        case 43:
            return `width-[43%]`;
        case 44:
            return `width-[44%]`;
        case 45:
            return `width-[45%]`;
        case 46:
            return `width-[46%]`;
        case 47:
            return `width-[47%]`;
        case 48:
            return `width-[48%]`;
        case 49:
            return `width-[49%]`;
        case 50:
            return `width-[50%]`;
        case 51:
            return `width-[51%]`;
        case 52:
            return `width-[52%]`;
        case 53:
            return `width-[53%]`;
        case 54:
            return `width-[54%]`;
        case 55:
            return `width-[55%]`;
        case 56:
            return `width-[56%]`;
        case 57:
            return `width-[57%]`;
        case 58:
            return `width-[58%]`;
        case 59:
            return `width-[59%]`;
        case 60:
            return `width-[60%]`;
        case 61:
            return `width-[61%]`;
        case 62:
            return `width-[62%]`;
        case 63:
            return `width-[63%]`;
        case 64:
            return `width-[64%]`;
        case 65:
            return `width-[65%]`;
        case 66:
            return `width-[66%]`;
        case 67:
            return `width-[67%]`;
        case 68:
            return `width-[68%]`;
        case 69:
            return `width-[69%]`;
        case 70:
            return `width-[70%]`;
        case 71:
            return `width-[71%]`;
        case 72:
            return `width-[72%]`;
        case 73:
            return `width-[73%]`;
        case 74:
            return `width-[74%]`;
        case 75:
            return `width-[75%]`;
        case 76:
            return `width-[76%]`;
        case 77:
            return `width-[77%]`;
        case 78:
            return `width-[78%]`;
        case 79:
            return `width-[79%]`;
        case 80:
            return `width-[80%]`;
        case 81:
            return `width-[81%]`;
        case 82:
            return `width-[82%]`;
        case 83:
            return `width-[83%]`;
        case 84:
            return `width-[84%]`;
        case 85:
            return `width-[85%]`;
        case 86:
            return `width-[86%]`;
        case 87:
            return `width-[87%]`;
        case 88:
            return `width-[88%]`;
        case 89:
            return `width-[89%]`;
        case 90:
            return `width-[90%]`;
        case 91:
            return `width-[91%]`;
        case 92:
            return `width-[92%]`;
        case 93:
            return `width-[93%]`;
        case 94:
            return `width-[94%]`;
        case 95:
            return `width-[95%]`;
        case 96:
            return `width-[96%]`;
        case 97:
            return `width-[97%]`;
        case 98:
            return `width-[98%]`;
        case 99:
            return `width-[99%]`;
        case 100:
            return `width-[100%]`;
        default:
            return `width-[${value}%]`;
    }
}

const getHeight = (value) => {
    switch (value) {
        case 1:
            return `height-[1%]`;
        case 2:
            return `height-[2%]`;
        case 3:
            return `height-[3%]`;
        case 4:
            return `height-[4%]`;
        case 5:
            return `height-[5%]`;
        case 6:
            return `height-[6%]`;
        case 7:
            return `height-[7%]`;
        case 8:
            return `height-[8%]`;
        case 9:
            return `height-[9%]`;
        case 10:
            return `height-[10%]`;
        case 11:
            return `height-[11%]`;
        case 12:
            return `height-[12%]`;
        case 13:
            return `height-[13%]`;
        case 14:
            return `height-[14%]`;
        case 15:
            return `height-[15%]`;
        case 16:
            return `height-[16%]`;
        case 17:
            return `height-[17%]`;
        case 18:
            return `height-[18%]`;
        case 19:
            return `height-[19%]`;
        case 20:
            return `height-[20%]`;
        case 21:
            return `height-[21%]`;
        case 22:
            return `height-[22%]`;
        case 23:
            return `height-[23%]`;
        case 24:
            return `height-[24%]`;
        case 25:
            return `height-[25%]`;
        case 26:
            return `height-[26%]`;
        case 27:
            return `height-[27%]`;
        case 28:
            return `height-[28%]`;
        case 29:
            return `height-[29%]`;
        case 30:
            return `height-[30%]`;
        case 31:
            return `height-[31%]`;
        case 32:
            return `height-[32%]`;
        case 33:
            return `height-[33%]`;
        case 34:
            return `height-[34%]`;
        case 35:
            return `height-[35%]`;
        case 36:
            return `height-[36%]`;
        case 37:
            return `height-[37%]`;
        case 38:
            return `height-[38%]`;
        case 39:
            return `height-[39%]`;
        case 40:
            return `height-[40%]`;
        case 41:
            return `height-[41%]`;
        case 42:
            return `height-[42%]`;
        case 43:
            return `height-[43%]`;
        case 44:
            return `height-[44%]`;
        case 45:
            return `height-[45%]`;
        case 46:
            return `height-[46%]`;
        case 47:
            return `height-[47%]`;
        case 48:
            return `height-[48%]`;
        case 49:
            return `height-[49%]`;
        case 50:
            return `height-[50%]`;
        case 51:
            return `height-[51%]`;
        case 52:
            return `height-[52%]`;
        case 53:
            return `height-[53%]`;
        case 54:
            return `height-[54%]`;
        case 55:
            return `height-[55%]`;
        case 56:
            return `height-[56%]`;
        case 57:
            return `height-[57%]`;
        case 58:
            return `height-[58%]`;
        case 59:
            return `height-[59%]`;
        case 60:
            return `height-[60%]`;
        case 61:
            return `height-[61%]`;
        case 62:
            return `height-[62%]`;
        case 63:
            return `height-[63%]`;
        case 64:
            return `height-[64%]`;
        case 65:
            return `height-[65%]`;
        case 66:
            return `height-[66%]`;
        case 67:
            return `height-[67%]`;
        case 68:
            return `height-[68%]`;
        case 69:
            return `height-[69%]`;
        case 70:
            return `height-[70%]`;
        case 71:
            return `height-[71%]`;
        case 72:
            return `height-[72%]`;
        case 73:
            return `height-[73%]`;
        case 74:
            return `height-[74%]`;
        case 75:
            return `height-[75%]`;
        case 76:
            return `height-[76%]`;
        case 77:
            return `height-[77%]`;
        case 78:
            return `height-[78%]`;
        case 79:
            return `height-[79%]`;
        case 80:
            return `height-[80%]`;
        case 81:
            return `height-[81%]`;
        case 82:
            return `height-[82%]`;
        case 83:
            return `height-[83%]`;
        case 84:
            return `height-[84%]`;
        case 85:
            return `height-[85%]`;
        case 86:
            return `height-[86%]`;
        case 87:
            return `height-[87%]`;
        case 88:
            return `height-[88%]`;
        case 89:
            return `height-[89%]`;
        case 90:
            return `height-[90%]`;
        case 91:
            return `height-[91%]`;
        case 92:
            return `height-[92%]`;
        case 93:
            return `height-[93%]`;
        case 94:
            return `height-[94%]`;
        case 95:
            return `height-[95%]`;
        case 96:
            return `height-[96%]`;
        case 97:
            return `height-[97%]`;
        case 98:
            return `height-[98%]`;
        case 99:
            return `height-[99%]`;
        case 100:
            return `height-[100%]`;
        default:
            return `height-[${value}%]`;
    }
}

